### ISSUE TITLE
Error when use node name

### ISSUE THREAD

**Issue by caiohasouza** [dkanbier/zabbix-elasticsearch#1]
Hello,

I'm trying use module with node name (es.domain.local) of my elasticsearch, but i have this error:

zbx_es.py  nodes.stats nodes.es.domain.local.indices.docs.count
Traceback (most recent call last):
  File "/tmp//zabbix-elasticsearch/zbx_es.py", line 73, in <module>
    returnval = config.get(key_string)
  File "/usr/lib/python2.6/site-packages/kaptan/__init__.py", line 95, in get
    raise KeyError(key)
KeyError: 'nodes.es.domain.local.indices.docs.count'

If i use ID all works:
zbx_es.py  nodes.stats nodes.l10Q__f6Tf65DZWlIbYvag.indices.docs.count
56841

Do you can help me please?

Best regards

**Comment by dkanbier** [comment]
I think it's because there are dots in the node name, which is not handled properly by the script. I'll try to fix this today, I think it can be fixed.

**Comment by caiohasouza** [comment]
Hi @dkanbier,

Perfect, thank very much! I'm waiting for you!

**Comment by dkanbier** [comment]
@xdexter please give the new commit a go and let me know if it works.

Regards!

**Comment by caiohasouza** [comment]
@dkanbier 

Perfect, now it works, thank you very much!

**Comment by dkanbier** [comment]
Thanks for the update!
