### ISSUE TITLE
Template won't import on 3.2

### ISSUE THREAD

**Issue by beaudh** [dkanbier/zabbix-elasticsearch#2]
When trying to import the template into Zabbix 3.2 I get:

Cannot find value map "ES Cluster State" used for item "ElasticSearch Cluster Status" on "Elastic search Cluster".

**Comment by beaudh** [comment]
Sorry I RTFM now :)

**Comment by ramya397** [comment]
i am also getting same error   what is the solution

**Comment by dkanbier** [comment]
Did you create the value map?  It's in the README:

"Before importing the zbx_es_templates.xml file be sure to create a value map called "ES Cluster State" which maps the proper values, like:

0 = Green
1 = Yellow
2 = Red
"

Also see: https://www.zabbix.com/documentation/3.2/manual/config/items/mapping?s[]=value&s[]=map
